import type {
  User,
  Workspace,
  Project,
  Task,
  KanbanColumn,
  TeamMember,
  Notification,
  CalendarEvent,
  ActivityItem,
  DashboardData,
  ReportOverview,
  SearchResult,
} from '@/types'

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Alex Morgan',
  email: 'alex@taskflow.io',
  avatarUrl: null,
  role: 'owner',
  timezone: 'America/New_York',
  createdAt: '2024-01-01T00:00:00Z',
}

export const MOCK_WORKSPACE: Workspace = {
  id: 'w1',
  name: 'Acme Inc',
  slug: 'acme-inc',
  plan: 'pro',
  logoUrl: null,
  ownerId: 'u1',
  memberCount: 6,
  createdAt: '2024-01-01T00:00:00Z',
}

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm1',
    userId: 'u1',
    name: 'Alex Morgan',
    email: 'alex@taskflow.io',
    avatarUrl: null,
    role: 'owner',
    workload: 78,
    lastActiveAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'tm2',
    userId: 'u2',
    name: 'Sophia Chen',
    email: 'sophia@taskflow.io',
    avatarUrl: null,
    role: 'admin',
    workload: 64,
    lastActiveAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'tm3',
    userId: 'u3',
    name: 'Marcus Lee',
    email: 'marcus@taskflow.io',
    avatarUrl: null,
    role: 'manager',
    workload: 91,
    lastActiveAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'tm4',
    userId: 'u4',
    name: 'Priya Patel',
    email: 'priya@taskflow.io',
    avatarUrl: null,
    role: 'member',
    workload: 52,
    lastActiveAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'tm5',
    userId: 'u5',
    name: 'Diego Ruiz',
    email: 'diego@taskflow.io',
    avatarUrl: null,
    role: 'member',
    workload: 73,
    lastActiveAt: new Date(Date.now() - 5400000).toISOString(),
  },
  {
    id: 'tm6',
    userId: 'u6',
    name: 'Hana Kim',
    email: 'hana@taskflow.io',
    avatarUrl: null,
    role: 'viewer',
    workload: 40,
    lastActiveAt: new Date(Date.now() - 10800000).toISOString(),
  },
]

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'Atlas Mobile App',
    description: 'Native mobile experience for iOS and Android platforms.',
    status: 'active',
    progress: 72,
    totalTasks: 48,
    completedTasks: 35,
    dueDate: '2026-08-15',
    members: [
      { userId: 'u1', name: 'Alex Morgan', avatarUrl: null },
      { userId: 'u2', name: 'Sophia Chen', avatarUrl: null },
      { userId: 'u5', name: 'Diego Ruiz', avatarUrl: null },
    ],
    isFavorited: true,
    createdById: 'u1',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-06-14T00:00:00Z',
  },
  {
    id: 'p2',
    name: 'Marketing Site Refresh',
    description: 'Complete redesign of the public marketing website.',
    status: 'at_risk',
    progress: 38,
    totalTasks: 32,
    completedTasks: 12,
    dueDate: '2026-06-30',
    members: [
      { userId: 'u2', name: 'Sophia Chen', avatarUrl: null },
      { userId: 'u4', name: 'Priya Patel', avatarUrl: null },
    ],
    isFavorited: false,
    createdById: 'u2',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-06-13T00:00:00Z',
  },
  {
    id: 'p3',
    name: 'Billing v2',
    description: 'Overhaul of the billing and subscription management system.',
    status: 'planning',
    progress: 18,
    totalTasks: 28,
    completedTasks: 5,
    dueDate: '2026-09-01',
    members: [
      { userId: 'u3', name: 'Marcus Lee', avatarUrl: null },
      { userId: 'u1', name: 'Alex Morgan', avatarUrl: null },
    ],
    isFavorited: false,
    createdById: 'u1',
    createdAt: '2026-03-15T00:00:00Z',
    updatedAt: '2026-06-10T00:00:00Z',
  },
  {
    id: 'p4',
    name: 'Design System 3.0',
    description: 'Next generation component library and design tokens.',
    status: 'active',
    progress: 96,
    totalTasks: 56,
    completedTasks: 54,
    dueDate: '2026-06-25',
    members: [
      { userId: 'u5', name: 'Diego Ruiz', avatarUrl: null },
      { userId: 'u2', name: 'Sophia Chen', avatarUrl: null },
      { userId: 'u6', name: 'Hana Kim', avatarUrl: null },
    ],
    isFavorited: true,
    createdById: 'u5',
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-06-15T00:00:00Z',
  },
  {
    id: 'p5',
    name: 'Onboarding Revamp',
    description: 'Improved new user onboarding flow with interactive guides.',
    status: 'completed',
    progress: 100,
    totalTasks: 24,
    completedTasks: 24,
    dueDate: '2026-05-31',
    members: [
      { userId: 'u4', name: 'Priya Patel', avatarUrl: null },
      { userId: 'u1', name: 'Alex Morgan', avatarUrl: null },
    ],
    isFavorited: false,
    createdById: 'u4',
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-05-30T00:00:00Z',
  },
  {
    id: 'p6',
    name: 'AI Insights Beta',
    description: 'AI-powered analytics and productivity insights feature.',
    status: 'active',
    progress: 54,
    totalTasks: 40,
    completedTasks: 22,
    dueDate: '2026-10-01',
    members: [
      { userId: 'u1', name: 'Alex Morgan', avatarUrl: null },
      { userId: 'u3', name: 'Marcus Lee', avatarUrl: null },
      { userId: 'u6', name: 'Hana Kim', avatarUrl: null },
    ],
    isFavorited: true,
    createdById: 'u1',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-06-14T00:00:00Z',
  },
]

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    projectId: 'p1',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment.',
    status: 'backlog',
    priority: 'high',
    assigneeId: 'u3',
    assignee: { id: 'u3', name: 'Marcus Lee', avatarUrl: null },
    dueDate: '2026-07-01',
    tags: ['Backend', 'DevOps'],
    columnId: 'backlog',
    order: 0,
    createdById: 'u1',
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-10T00:00:00Z',
  },
  {
    id: 't2',
    projectId: 'p1',
    title: 'Design authentication screens',
    description: null,
    status: 'backlog',
    priority: 'medium',
    assigneeId: 'u5',
    assignee: { id: 'u5', name: 'Diego Ruiz', avatarUrl: null },
    dueDate: '2026-06-25',
    tags: ['Design', 'Mobile'],
    columnId: 'backlog',
    order: 1,
    createdById: 'u2',
    createdAt: '2026-06-02T00:00:00Z',
    updatedAt: '2026-06-11T00:00:00Z',
  },
  {
    id: 't3',
    projectId: 'p1',
    title: 'Implement push notifications',
    description: 'iOS and Android push notification support via FCM.',
    status: 'todo',
    priority: 'high',
    assigneeId: 'u3',
    assignee: { id: 'u3', name: 'Marcus Lee', avatarUrl: null },
    dueDate: '2026-07-10',
    tags: ['Backend', 'Mobile'],
    columnId: 'todo',
    order: 0,
    createdById: 'u1',
    createdAt: '2026-06-03T00:00:00Z',
    updatedAt: '2026-06-12T00:00:00Z',
  },
  {
    id: 't4',
    projectId: 'p2',
    title: 'Pricing page copy',
    description: null,
    status: 'todo',
    priority: 'urgent',
    assigneeId: 'u4',
    assignee: { id: 'u4', name: 'Priya Patel', avatarUrl: null },
    dueDate: '2026-06-19',
    tags: ['Content'],
    columnId: 'todo',
    order: 1,
    createdById: 'u2',
    createdAt: '2026-06-05T00:00:00Z',
    updatedAt: '2026-06-14T00:00:00Z',
  },
  {
    id: 't5',
    projectId: 'p1',
    title: 'QA pass on iOS build',
    description: 'Full regression test on iOS 17 and 18 simulators.',
    status: 'in_progress',
    priority: 'high',
    assigneeId: 'u1',
    assignee: { id: 'u1', name: 'Alex Morgan', avatarUrl: null },
    dueDate: '2026-06-28',
    tags: ['QA', 'Mobile'],
    columnId: 'in_progress',
    order: 0,
    createdById: 'u1',
    createdAt: '2026-06-06T00:00:00Z',
    updatedAt: '2026-06-15T00:00:00Z',
  },
  {
    id: 't6',
    projectId: 'p4',
    title: 'Hero animation polish',
    description: 'Refine entrance animations for hero section components.',
    status: 'in_progress',
    priority: 'medium',
    assigneeId: 'u5',
    assignee: { id: 'u5', name: 'Diego Ruiz', avatarUrl: null },
    dueDate: '2026-06-20',
    tags: ['Design', 'Animation'],
    columnId: 'in_progress',
    order: 1,
    createdById: 'u5',
    createdAt: '2026-06-07T00:00:00Z',
    updatedAt: '2026-06-15T00:00:00Z',
  },
  {
    id: 't7',
    projectId: 'p6',
    title: 'Token migration script',
    description: 'Script to migrate legacy auth tokens to new format.',
    status: 'in_progress',
    priority: 'urgent',
    assigneeId: 'u2',
    assignee: { id: 'u2', name: 'Sophia Chen', avatarUrl: null },
    dueDate: '2026-06-18',
    tags: ['Backend', 'Security'],
    columnId: 'in_progress',
    order: 2,
    createdById: 'u3',
    createdAt: '2026-06-08T00:00:00Z',
    updatedAt: '2026-06-15T00:00:00Z',
  },
  {
    id: 't8',
    projectId: 'p4',
    title: 'Audit billing endpoints',
    description: null,
    status: 'review',
    priority: 'high',
    assigneeId: 'u3',
    assignee: { id: 'u3', name: 'Marcus Lee', avatarUrl: null },
    dueDate: '2026-06-28',
    tags: ['Backend', 'Billing'],
    columnId: 'review',
    order: 0,
    createdById: 'u3',
    createdAt: '2026-06-09T00:00:00Z',
    updatedAt: '2026-06-15T00:00:00Z',
  },
  {
    id: 't9',
    projectId: 'p2',
    title: 'Design new onboarding flow',
    description: 'Wireframes and high-fidelity mockups for the new onboarding.',
    status: 'review',
    priority: 'medium',
    assigneeId: 'u4',
    assignee: { id: 'u4', name: 'Priya Patel', avatarUrl: null },
    dueDate: '2026-06-22',
    tags: ['Design', 'UX'],
    columnId: 'review',
    order: 1,
    createdById: 'u4',
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-14T00:00:00Z',
  },
  {
    id: 't10',
    projectId: 'p4',
    title: 'Update icon library',
    description: null,
    status: 'done',
    priority: 'low',
    assigneeId: 'u6',
    assignee: { id: 'u6', name: 'Hana Kim', avatarUrl: null },
    dueDate: '2026-06-10',
    tags: ['Design'],
    columnId: 'done',
    order: 0,
    createdById: 'u5',
    createdAt: '2026-05-20T00:00:00Z',
    updatedAt: '2026-06-09T00:00:00Z',
  },
  {
    id: 't11',
    projectId: 'p5',
    title: 'Write onboarding copy',
    description: null,
    status: 'done',
    priority: 'medium',
    assigneeId: 'u4',
    assignee: { id: 'u4', name: 'Priya Patel', avatarUrl: null },
    dueDate: '2026-05-28',
    tags: ['Content'],
    columnId: 'done',
    order: 1,
    createdById: 'u4',
    createdAt: '2026-05-10T00:00:00Z',
    updatedAt: '2026-05-27T00:00:00Z',
  },
  {
    id: 't12',
    projectId: 'p6',
    title: 'User research interviews',
    description: 'Conduct 5 user interviews for AI feature validation.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 'u6',
    assignee: { id: 'u6', name: 'Hana Kim', avatarUrl: null },
    dueDate: '2026-07-05',
    tags: ['Research'],
    columnId: 'todo',
    order: 2,
    createdById: 'u1',
    createdAt: '2026-06-12T00:00:00Z',
    updatedAt: '2026-06-12T00:00:00Z',
  },
  {
    id: 't13',
    projectId: 'p1',
    title: 'Accessibility audit',
    description: null,
    status: 'backlog',
    priority: 'low',
    assigneeId: 'u6',
    assignee: { id: 'u6', name: 'Hana Kim', avatarUrl: null },
    dueDate: '2026-07-20',
    tags: ['QA', 'Accessibility'],
    columnId: 'backlog',
    order: 2,
    createdById: 'u1',
    createdAt: '2026-06-13T00:00:00Z',
    updatedAt: '2026-06-13T00:00:00Z',
  },
  {
    id: 't14',
    projectId: 'p6',
    title: 'Case study: Acme Inc',
    description: 'Document the Acme Inc implementation as a public case study.',
    status: 'done',
    priority: 'low',
    assigneeId: 'u2',
    assignee: { id: 'u2', name: 'Sophia Chen', avatarUrl: null },
    dueDate: '2026-06-10',
    tags: ['Marketing'],
    columnId: 'done',
    order: 2,
    createdById: 'u2',
    createdAt: '2026-05-25T00:00:00Z',
    updatedAt: '2026-06-10T00:00:00Z',
  },
]

export function getMockKanbanColumns(): KanbanColumn[] {
  const columns = [
    { id: 'backlog', name: 'Backlog', status: 'backlog' as const, order: 0 },
    { id: 'todo', name: 'To Do', status: 'todo' as const, order: 1 },
    { id: 'in_progress', name: 'In Progress', status: 'in_progress' as const, order: 2 },
    { id: 'review', name: 'Review', status: 'review' as const, order: 3 },
    { id: 'done', name: 'Done', status: 'done' as const, order: 4 },
  ]

  return columns.map((col) => ({
    ...col,
    tasks: MOCK_TASKS.filter((t) => t.columnId === col.id).sort(
      (a, b) => a.order - b.order
    ),
    taskCount: MOCK_TASKS.filter((t) => t.columnId === col.id).length,
  }))
}

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'assignment',
    message: 'Sophia Chen assigned Pricing page copy to you',
    actorId: 'u2',
    actorName: 'Sophia Chen',
    actorAvatarUrl: null,
    resourceId: 't4',
    resourceType: 'task',
    isRead: false,
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    id: 'n2',
    type: 'completion',
    message: 'Alex Morgan created project AI Insights Beta',
    actorId: 'u1',
    actorName: 'Alex Morgan',
    actorAvatarUrl: null,
    resourceId: 'p6',
    resourceType: 'project',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'n3',
    type: 'mention',
    message: 'Marcus Lee mentioned you in Billing v2',
    actorId: 'u3',
    actorName: 'Marcus Lee',
    actorAvatarUrl: null,
    resourceId: 'p3',
    resourceType: 'project',
    isRead: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'n4',
    type: 'comment',
    message: 'Priya Patel commented on Design new onboarding flow',
    actorId: 'u4',
    actorName: 'Priya Patel',
    actorAvatarUrl: null,
    resourceId: 't9',
    resourceType: 'task',
    isRead: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'n5',
    type: 'assignment',
    message: 'Diego Ruiz assigned Hero animation polish to you',
    actorId: 'u5',
    actorName: 'Diego Ruiz',
    actorAvatarUrl: null,
    resourceId: 't6',
    resourceType: 'task',
    isRead: true,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'n6',
    type: 'invitation',
    message: 'Hana Kim was added to the workspace',
    actorId: 'u1',
    actorName: 'Alex Morgan',
    actorAvatarUrl: null,
    resourceId: 'w1',
    resourceType: 'project',
    isRead: true,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
]

export const MOCK_CALENDAR_EVENTS: CalendarEvent[] = [
  { id: 'ce1', title: 'Case study: Acme Inc', date: '2026-06-10', type: 'deadline', projectId: 'p6', assigneeId: 'u2' },
  { id: 'ce2', title: 'Token migration script', date: '2026-06-18', type: 'deadline', projectId: 'p6', assigneeId: 'u2' },
  { id: 'ce3', title: 'Pricing page copy', date: '2026-06-19', type: 'deadline', projectId: 'p2', assigneeId: 'u4' },
  { id: 'ce4', title: 'Hero animation polish', date: '2026-06-20', type: 'deadline', projectId: 'p4', assigneeId: 'u5' },
  { id: 'ce5', title: 'Design new onboarding flow', date: '2026-06-22', type: 'deadline', projectId: 'p2', assigneeId: 'u4' },
  { id: 'ce6', title: 'QA pass on iOS build', date: '2026-06-28', type: 'deadline', projectId: 'p1', assigneeId: 'u1' },
  { id: 'ce7', title: 'Audit billing endpoints', date: '2026-06-28', type: 'deadline', projectId: 'p4', assigneeId: 'u3' },
  { id: 'ce8', title: 'User research interviews', date: '2026-07-05', type: 'task', projectId: 'p6', assigneeId: 'u6' },
  { id: 'ce9', title: 'Design System 3.0 launch', date: '2026-06-25', type: 'deadline', projectId: 'p4', assigneeId: 'u5' },
]

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: 'a1',
    actorName: 'Sophia Chen',
    actorAvatarUrl: null,
    action: 'assigned',
    resourceName: 'Pricing page copy',
    resourceId: 't4',
    resourceType: 'task',
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    id: 'a2',
    actorName: 'Alex Morgan',
    actorAvatarUrl: null,
    action: 'created project',
    resourceName: 'AI Insights Beta',
    resourceId: 'p6',
    resourceType: 'project',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'a3',
    actorName: 'Marcus Lee',
    actorAvatarUrl: null,
    action: 'completed',
    resourceName: 'Audit billing endpoints',
    resourceId: 't8',
    resourceType: 'task',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'a4',
    actorName: 'Priya Patel',
    actorAvatarUrl: null,
    action: 'updated',
    resourceName: 'Design new onboarding flow',
    resourceId: 't9',
    resourceType: 'task',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'a5',
    actorName: 'Diego Ruiz',
    actorAvatarUrl: null,
    action: 'commented on',
    resourceName: 'Hero animation polish',
    resourceId: 't6',
    resourceType: 'task',
    createdAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
  },
]

export const MOCK_DASHBOARD: DashboardData = {
  metrics: {
    activeProjects: 12,
    activeProjectsDelta: 8.2,
    totalTasks: 284,
    totalTasksDelta: 12.4,
    completed: 176,
    completedDelta: 4.7,
    overdue: 9,
    overdueDelta: -2.1,
  },
  recentActivity: MOCK_ACTIVITY,
  upcomingDeadlines: [
    { id: 't9', date: '2026-06-22', taskName: 'Design new onboarding flow', assigneeName: 'Priya Patel', assigneeAvatarUrl: null },
    { id: 't8', date: '2026-06-28', taskName: 'Audit billing endpoints', assigneeName: 'Marcus Lee', assigneeAvatarUrl: null },
    { id: 't6', date: '2026-06-20', taskName: 'Hero animation polish', assigneeName: 'Diego Ruiz', assigneeAvatarUrl: null },
    { id: 't7', date: '2026-06-18', taskName: 'Token migration script', assigneeName: 'Sophia Chen', assigneeAvatarUrl: null },
  ],
  projectProgress: MOCK_PROJECTS.map((p) => ({
    id: p.id,
    name: p.name,
    status: p.status,
    progress: p.progress,
  })),
  productivityData: [
    { day: 'Mon', created: 8, completed: 6 },
    { day: 'Tue', created: 12, completed: 10 },
    { day: 'Wed', created: 14, completed: 11 },
    { day: 'Thu', created: 10, completed: 12 },
    { day: 'Fri', created: 16, completed: 14 },
    { day: 'Sat', created: 4, completed: 6 },
    { day: 'Sun', created: 2, completed: 3 },
  ],
  completionRate: 89,
  completionRateDelta: 27,
}

export const MOCK_REPORTS: ReportOverview = {
  metrics: {
    velocity: 47,
    velocityDelta: 12,
    avgCycleTime: 3.2,
    cycleTimeDelta: -0.4,
    onTimeDelivery: 89,
    onTimeDelta: 5,
    activeContributors: 6,
    rolesCount: 4,
  },
  productivityTrend: [
    { week: 'W1', completionRate: 62 },
    { week: 'W2', completionRate: 68 },
    { week: 'W3', completionRate: 71 },
    { week: 'W4', completionRate: 65 },
    { week: 'W5', completionRate: 78 },
    { week: 'W6', completionRate: 82 },
    { week: 'W7', completionRate: 85 },
    { week: 'W8', completionRate: 89 },
  ],
  projectMix: [
    { status: 'active', count: 4 },
    { status: 'planning', count: 2 },
    { status: 'at_risk', count: 1 },
    { status: 'completed', count: 5 },
  ],
  teamPerformance: [
    { day: 'Mon', created: 8, completed: 6 },
    { day: 'Tue', created: 12, completed: 10 },
    { day: 'Wed', created: 14, completed: 11 },
    { day: 'Thu', created: 10, completed: 12 },
    { day: 'Fri', created: 16, completed: 14 },
    { day: 'Sat', created: 4, completed: 6 },
    { day: 'Sun', created: 2, completed: 3 },
  ],
  workloadDistribution: [
    { name: 'Alex', workload: 78 },
    { name: 'Sophia', workload: 64 },
    { name: 'Marcus', workload: 91 },
    { name: 'Priya', workload: 52 },
    { name: 'Diego', workload: 73 },
    { name: 'Hana', workload: 40 },
  ],
}

export function getMockSearchResults(query: string): SearchResult {
  const q = query.toLowerCase()
  return {
    tasks: MOCK_TASKS.filter((t) => t.title.toLowerCase().includes(q)).slice(0, 5),
    projects: MOCK_PROJECTS.filter((p) => p.name.toLowerCase().includes(q)).slice(0, 3),
    members: MOCK_TEAM_MEMBERS.filter(
      (m) => m.name.toLowerCase().includes(q) || m.email.toLowerCase().includes(q)
    ).slice(0, 3),
  }
}
